-- ==========================================================
-- REPORT 1
-- Active Customers
-- Purpose:
-- Displays all customers with currently active subscriptions.
-- ==========================================================

SELECT *
FROM vw_ActiveCustomers;

-- ==========================================================
-- REPORT 2
-- Pending Payments
-- Purpose:
-- Displays all payments that are awaiting completion.
-- ==========================================================

SELECT *
FROM vw_PendingPayments;

-- ==========================================================
-- REPORT 3
-- Customer Subscription History
-- Purpose:
-- Displays every customer's subscription history.
-- ==========================================================

SELECT *
FROM vw_SubscriptionHistory
ORDER BY CustomerID;

-- ==========================================================
-- REPORT 4
-- Revenue Generated by Plan
-- Purpose:
-- Displays total completed revenue generated by each plan.
-- ==========================================================

SELECT *
FROM vw_RevenueByPlan
ORDER BY Revenue DESC;

-- ==========================================================
-- REPORT 5
-- Total Active Customers
-- Purpose:
-- Displays the total number of active subscribers.
-- ==========================================================

SELECT
COUNT(*) AS TotalActiveCustomers
FROM vw_ActiveCustomers;

-- ==========================================================
-- REPORT 6
-- Total Pending Payments
-- Purpose:
-- Displays the total number of pending payments.
-- ==========================================================

SELECT
COUNT(*) AS PendingPayments
FROM vw_PendingPayments;

-- ==========================================================
-- REPORT 7
-- Highest Revenue Generating Plan
-- Purpose:
-- Displays the plan with the highest completed revenue.
-- ==========================================================

SELECT *
FROM vw_RevenueByPlan
ORDER BY Revenue DESC
LIMIT 1;

-- ==========================================================
-- REPORT 8
-- Active Customers by City
-- Purpose:
-- Shows how many active subscribers belong to each city.
-- ==========================================================

SELECT
City,
COUNT(CustomerID) AS TotalCustomers
FROM vw_ActiveCustomers
GROUP BY City
ORDER BY TotalCustomers DESC;